### PR TITLE
Adds stale bot config

### PR DESCRIPTION
**Pull request by abea**
We'll install the bot following merge: https://github.com/apps/stale

### CODE REVIEW

**Comment by abea** [comment]
Does this look like reasonable config? I made it more generous than the default suggested.

**Comment by boutell** [comment]
If we turned this on for the apostrophe repo today, it would wind up closing many "gotta do before 3.x comes out" issues.

**Review by boutell — CHANGES_REQUESTED** [review]
If we turned this on for the apostrophe repo today, it would wind up closing many "gotta do before 3.x comes out" issues. I think?

**Comment by abea** [comment]
Good point. I've added `3.0` to the exempt labels, as well as a theoretical `next-major` since not all have 3.x as their next major version. We can workshop that one.

**Review by boutell — APPROVED** [review]

**Pull request merged**
